name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "!v*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git config --global --add safe.directory '*'

    - name: Download VGG19 weights
      run: wget -O VGG_Model.zip "https://hkustconnect-my.sharepoint.com/:u:/g/personal/cleiaa_connect_ust_hk/EZeGsvuqh1dJr0E2Fxf6IKoBQ7wZpGi3NFqZxhzC8-3GHg?e=LLWUZT&download=1"

    - name: Download checkpoint
      run: wget -O result.zip "https://www.dropbox.com/scl/fi/26p8e04i0vf4wn3mf9zad/result.zip?rlkey=3zx74ym8m1prejdee2rcdi6kj&dl=0"

    - name: Build docker image
      run: docker build -f ./docker/app.dockerfile -t deglare-app .
